using Content.Shared.Cargo;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Cargo.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class CargoProductRow : BoxContainer
    {
        public CargoProductPrototype? Product { get; set; }
        public WeeklyCargoProductData? WeeklyProduct { get; set; }
        public string ProductId { get; set; } = string.Empty;

        public CargoProductRow()
        {
            RobustXamlLoader.Load(this);
        }
    }
}
